/* ============================================================
   THATWAY · CAB — WEG-ANWEISUNGEN (auto: kontextuell)
   ------------------------------------------------------------
   Pro Raum: ein Text je Schritt (in Reihenfolge).
   "Take the elevator to Floor X" = Aufzug-Schritt (nicht loeschen).
   Letzter Eintrag "" = Ankunft (wird ignoriert).
   Du kannst einzelne Texte jederzeit von Hand ueberschreiben,
   z.B. mit einer Landmarke: "Left at the directory".
   ============================================================ */
const DIRECTIONS = {
  "B101": [""],
  "B103": ["Head down the corridor",""],
  "B104": ["Head down the corridor","Keep going","Almost there",""],
  "B105": ["Head down the corridor","Keep going","Keep going","Almost there",""],
  "B108": ["Head down the corridor","Keep going","Almost there",""],
  "B114": ["Head down the corridor","Almost there",""],
  "B115": ["Head down the corridor","Almost there",""],
  "B116": ["Head down the corridor","Almost there",""],
  "B117": ["Head down the corridor","Almost there",""],
  "B123": ["Head down the corridor","Almost there",""],
  "B124": ["Head down the corridor","Almost there",""],
  "B128": ["Head down the corridor","Almost there",""],
  "B134": ["Head down the corridor","Keep going","Almost there",""],
  "B135": ["Head down the corridor",""],
  "B135A": ["Head down the corridor","Almost there",""],
  "B201": ["Head down the corridor","Keep going","Take the elevator to Floor 2","Step out and keep going","Keep going","Almost there",""],
  "B202": ["Head down the corridor","Keep going","Take the elevator to Floor 2","Step out and keep going","Keep going","Almost there",""],
  "B203": ["Head down the corridor","Almost there","Take the elevator to Floor 2",""],
  "B208": ["Head down the corridor","Keep going","Take the elevator to Floor 2","Step out and keep going","Keep going","Almost there",""],
  "B209": ["Head down the corridor","Keep going","Take the elevator to Floor 2","Step out and keep going","Keep going","Almost there",""],
  "B210": ["Head down the corridor","Keep going","Take the elevator to Floor 2","Step out and keep going","Keep going","Almost there",""],
  "B211": ["Head down the corridor","Keep going","Take the elevator to Floor 2","Step out and keep going","Keep going","Almost there",""],
  "B216": ["Head down the corridor","Keep going","Take the elevator to Floor 2","Step out and keep going","Almost there",""],
  "B217": ["Head down the corridor","Keep going","Take the elevator to Floor 2","Step out and keep going","Almost there",""],
  "B218": ["Head down the corridor","Keep going","Take the elevator to Floor 2","Step out and keep going","Almost there",""],
  "B219": ["Head down the corridor","Keep going","Take the elevator to Floor 2","Step out and keep going",""],
  "B220": ["Head down the corridor","Keep going","Take the elevator to Floor 2","Step out and keep going",""],
  "B221": ["Head down the corridor","Keep going","Take the elevator to Floor 2","Step out and keep going","Almost there",""],
  "B222": ["Head down the corridor","Keep going","Take the elevator to Floor 2","Step out and keep going","Keep going","Almost there",""],
  "B223": ["Head down the corridor","Keep going","Take the elevator to Floor 2","Step out and keep going",""],
  "B225": ["Head down the corridor","Keep going","Take the elevator to Floor 2","Step out and keep going","Almost there",""],
  "B226": ["Head down the corridor","Keep going","Take the elevator to Floor 2","Step out and keep going","Almost there",""],
  "B231": ["Head down the corridor","Keep going","Take the elevator to Floor 2","Step out and keep going","Keep going","Almost there",""],
  "B232": ["Head down the corridor","Keep going","Take the elevator to Floor 2","Step out and keep going","Keep going","Almost there",""],
  "B233": ["Head down the corridor","Keep going","Take the elevator to Floor 2","Step out and keep going","Keep going","Almost there",""],
  "B301": ["Head down the corridor","Keep going","Take the elevator to Floor 3","Step out and keep going","Almost there",""],
  "B302": ["Head down the corridor","Almost there","Take the elevator to Floor 3",""],
  "B307": ["Head down the corridor","Keep going","Take the elevator to Floor 3","Step out and keep going",""],
  "B310": ["Head down the corridor","Almost there","Take the elevator to Floor 3",""],
  "B312": ["Head down the corridor","Almost there","Take the elevator to Floor 3",""],
  "B313": ["Head down the corridor","Keep going","Take the elevator to Floor 3","Step out and keep going",""],
  "B318": ["Head down the corridor","Keep going","Take the elevator to Floor 3","Step out and keep going","Almost there",""],
  "B319": ["Head down the corridor","Keep going","Take the elevator to Floor 3","Step out and keep going","Almost there",""],
  "B320": ["Head down the corridor","Keep going","Take the elevator to Floor 3","Step out and keep going","Keep going","Almost there",""],
  "B321": ["Head down the corridor","Keep going","Take the elevator to Floor 3","Step out and keep going","Keep going","Almost there",""],
  "B323": ["Head down the corridor","Keep going","Take the elevator to Floor 3","Step out and keep going","Almost there",""],
  "B324": ["Head down the corridor","Keep going","Take the elevator to Floor 3","Step out and keep going","Almost there",""],
  "B325": ["Head down the corridor","Keep going","Take the elevator to Floor 3","Step out and keep going","Almost there",""],
  "B326": ["Head down the corridor","Keep going","Take the elevator to Floor 3","Step out and keep going","Almost there",""],
  "B331": ["Head down the corridor","Keep going","Take the elevator to Floor 3","Step out and keep going",""],
  "B332": ["Head down the corridor","Keep going","Take the elevator to Floor 3","Step out and keep going",""],
  "B333": ["Head down the corridor","Keep going","Take the elevator to Floor 3","Step out and keep going",""],
  "B334": ["Head down the corridor","Keep going","Take the elevator to Floor 3","Step out and keep going",""],
  "B337": ["Head down the corridor","Keep going","Take the elevator to Floor 3","Step out and keep going",""],
  "B338": ["Head down the corridor","Keep going","Take the elevator to Floor 3","Step out and keep going",""],
  "B339": ["Head down the corridor","Keep going","Take the elevator to Floor 3","Step out and keep going",""],
  "B340": ["Head down the corridor","Keep going","Take the elevator to Floor 3","Step out and keep going",""],
  "B345": ["Head down the corridor","Keep going","Take the elevator to Floor 3","Step out and keep going","Almost there",""],
  "B347": ["Head down the corridor","Keep going","Take the elevator to Floor 3","Step out and keep going","Keep going","Almost there",""],
  "B348": ["Head down the corridor","Keep going","Take the elevator to Floor 3","Step out and keep going","Keep going","Almost there",""],
  "B349": ["Head down the corridor","Keep going","Take the elevator to Floor 3","Step out and keep going","Almost there",""],
  "B350": ["Head down the corridor","Keep going","Take the elevator to Floor 3","Step out and keep going","Almost there",""],
  "B351": ["Head down the corridor","Keep going","Take the elevator to Floor 3","Step out and keep going",""],
  "B401": ["Head down the corridor","Keep going","Take the elevator to Floor 4","Step out and keep going",""],
  "B402": ["Head down the corridor","Keep going","Take the elevator to Floor 4","Step out and keep going","Almost there",""],
  "B405": ["Head down the corridor","Keep going","Take the elevator to Floor 4","Step out and keep going",""],
  "B409": ["Head down the corridor","Keep going","Take the elevator to Floor 4","Step out and keep going","Keep going","Almost there",""],
  "B410": ["Head down the corridor","Keep going","Take the elevator to Floor 4","Step out and keep going","Keep going","Almost there",""],
  "B411": ["Head down the corridor","Keep going","Take the elevator to Floor 4","Step out and keep going","Keep going","Almost there",""],
  "B416": ["Head down the corridor","Keep going","Take the elevator to Floor 4","Step out and keep going","Almost there",""],
  "B417": ["Head down the corridor","Keep going","Take the elevator to Floor 4","Step out and keep going","Almost there",""],
  "B418": ["Head down the corridor","Keep going","Take the elevator to Floor 4","Step out and keep going","Almost there",""],
  "B419": ["Head down the corridor","Keep going","Take the elevator to Floor 4","Step out and keep going","Almost there",""],
  "B420": ["Head down the corridor","Keep going","Take the elevator to Floor 4","Step out and keep going",""],
  "B421": ["Head down the corridor","Keep going","Take the elevator to Floor 4","Step out and keep going",""],
  "B427": ["Head down the corridor","Keep going","Take the elevator to Floor 4","Step out and keep going",""],
  "B428": ["Head down the corridor","Keep going","Take the elevator to Floor 4","Step out and keep going",""],
  "B429": ["Head down the corridor","Keep going","Take the elevator to Floor 4","Step out and keep going",""],
  "B434": ["Head down the corridor","Keep going","Take the elevator to Floor 4","Step out and keep going","Almost there",""],
  "B435": ["Head down the corridor","Keep going","Take the elevator to Floor 4","Step out and keep going","Almost there",""],
  "B439": ["Head down the corridor","Almost there","Take the elevator to Floor 4",""],
  "DINING": ["Head down the corridor","Keep going","Keep going","Almost there",""],
};
