/* ============================================================
   THATWAY — KARTE (Floor 1, echte Fotos & Wegpunkte)
   Wegpunkte + Verbindungen + Räume. Blaue Linien pro Verbindung
   ziehst du im ✏️-Editor der App (dann 💾 Export -> an Claude).
   ============================================================ */
const DEFAULT_START = 'f1-lobby-e1';   // Haupt-Eingangschip = Lobby B101

const WAYPOINTS = {
  'f1-dining-w': { img:'panos/f1-dining-w.jpg', floor:'Floor 1' },
  'f1-corr-w': { img:'panos/f1-corr-w.jpg', floor:'Floor 1' },
  'f1-elev-w': { img:'panos/f1-elev-w.jpg', floor:'Floor 1' },
  'f1-corr-e3': { img:'panos/f1-corr-e3.jpg', floor:'Floor 1' },
  'f1-lobby-e1': { img:'panos/f1-lobby-e1.jpg', floor:'Floor 1' },
  'f1-corr-e2': { img:'panos/f1-corr-e2.jpg', floor:'Floor 1' },
  'f1-elev-e2': { img:'panos/f1-elev-e2.jpg', floor:'Floor 1' },
  'f1-elev-e3': { img:'panos/f1-elev-e3.jpg', floor:'Floor 1' },
  'f1-game-e': { img:'panos/f1-game-e.jpg', floor:'Floor 1' },
  'f1-corner-e1': { img:'panos/f1-corner-e1.jpg', floor:'Floor 1' },
  /* ---- Floor 2 ---- */
  'f2-hall-w': { img:'panos/f2-hall-w.jpg', floor:'Floor 2' },
  'f2-its-w': { img:'panos/f2-its-w.jpg', floor:'Floor 2' },
  'f2-corr-w': { img:'panos/f2-corr-w.jpg', floor:'Floor 2' },
  'f2-elev-w2': { img:'panos/f2-elev-w2.jpg', floor:'Floor 2' },
  'f2-eleve-w': { img:'panos/f2-eleve-w.jpg', floor:'Floor 2' },
  'f2-elev-w1': { img:'panos/f2-elev-w1.jpg', floor:'Floor 2' },
  'f2-stair-e2': { img:'panos/f2-stair-e2.jpg', floor:'Floor 2' },
  'f2-tutor-e1': { img:'panos/f2-tutor-e1.jpg', floor:'Floor 2' },
  'f2-stair-e3': { img:'panos/f2-stair-e3.jpg', floor:'Floor 2' },
  'f2-elev-ex2': { img:'panos/f2-elev-ex2.jpg', floor:'Floor 2' },
  'f2-elev-e': { img:'panos/f2-elev-e.jpg', floor:'Floor 2' },
  'f2-elev-ex-e': { img:'panos/f2-elev-ex-e.jpg', floor:'Floor 2' },
  'f2-clep-e': { img:'panos/f2-clep-e.jpg', floor:'Floor 2' },
  'f2-hall-e1': { img:'panos/f2-hall-e1.jpg', floor:'Floor 2' },
  'f2-corr-e': { img:'panos/f2-corr-e.jpg', floor:'Floor 2' },
  /* ---- Floor 3 ---- */
  'f3-corner-w1': { img:'panos/f3-corner-w1.jpg', floor:'Floor 3' },
  'f3-hall-w': { img:'panos/f3-hall-w.jpg', floor:'Floor 3' },
  'f3-corr-w': { img:'panos/f3-corr-w.jpg', floor:'Floor 3' },
  'f3-elev-w': { img:'panos/f3-elev-w.jpg', floor:'Floor 3' },
  'f3-stair-w2': { img:'panos/f3-stair-w2.jpg', floor:'Floor 3' },
  'f3-vest-e': { img:'panos/f3-vest-e.jpg', floor:'Floor 3' },
  'f3-stair-e2': { img:'panos/f3-stair-e2.jpg', floor:'Floor 3' },
  'f3-elev-e': { img:'panos/f3-elev-e.jpg', floor:'Floor 3' },
  'f3-corr-e': { img:'panos/f3-corr-e.jpg', floor:'Floor 3' },
  'f3-corner-e1': { img:'panos/f3-corner-e1.jpg', floor:'Floor 3' },
  'f3-hall-e': { img:'panos/f3-hall-e.jpg', floor:'Floor 3' },
  /* ---- Floor 4 ---- */
  'f4-provost-w1': { img:'panos/f4-provost-w1.jpg', floor:'Floor 4' },
  'f4-hall-w4': { img:'panos/f4-hall-w4.jpg', floor:'Floor 4' },
  'f4-corr-w': { img:'panos/f4-corr-w.jpg', floor:'Floor 4' },
  'f4-elev-w': { img:'panos/f4-elev-w.jpg', floor:'Floor 4' },
  'f4-stair-w2': { img:'panos/f4-stair-w2.jpg', floor:'Floor 4' },
  'f4-vista-e3': { img:'panos/f4-vista-e3.jpg', floor:'Floor 4' },
  'f4-stair-e2': { img:'panos/f4-stair-e2.jpg', floor:'Floor 4' },
  'f4-elev-e': { img:'panos/f4-elev-e.jpg', floor:'Floor 4' },
  'f4-elev-e-1': { img:'panos/f4-elev-e-1.jpg', floor:'Floor 4' },
  'f4-corr-e': { img:'panos/f4-corr-e.jpg', floor:'Floor 4' },
  'f4-wing-e': { img:'panos/f4-wing-e.jpg', floor:'Floor 4' },
  'f4-president-e1': { img:'panos/f4-president-e1.jpg', floor:'Floor 4' },
};

const EDGES = [
  { from:'f1-corr-w', to:'f1-dining-w', big:'Follow the line', sub:'', line:[] },
  { from:'f1-dining-w', to:'f1-corr-w', big:'Follow the line', sub:'', line:[] },
  { from:'f1-corr-w', to:'f1-elev-w', big:'Follow the line', sub:'', line:[] },
  { from:'f1-elev-w', to:'f1-corr-w', big:'Follow the line', sub:'', line:[] },
  { from:'f1-elev-w', to:'f1-corr-e3', big:'Follow the line', sub:'', line:[] },
  { from:'f1-corr-e3', to:'f1-elev-w', big:'Follow the line', sub:'', line:[] },
  { from:'f1-corr-e3', to:'f1-lobby-e1', big:'Follow the line', sub:'', line:[] },
  { from:'f1-lobby-e1', to:'f1-corr-e3', big:'Follow the line', sub:'', line:[] },
  { from:'f1-lobby-e1', to:'f1-corr-e2', big:'Follow the line', sub:'', line:[] },
  { from:'f1-corr-e2', to:'f1-lobby-e1', big:'Follow the line', sub:'', line:[] },
  { from:'f1-corr-e2', to:'f1-elev-e2', big:'Follow the line', sub:'', line:[] },
  { from:'f1-elev-e2', to:'f1-corr-e2', big:'Follow the line', sub:'', line:[] },
  { from:'f1-elev-e2', to:'f1-elev-e3', big:'Follow the line', sub:'', line:[] },
  { from:'f1-elev-e3', to:'f1-elev-e2', big:'Follow the line', sub:'', line:[] },
  { from:'f1-elev-e2', to:'f1-game-e', big:'Follow the line', sub:'', line:[] },
  { from:'f1-game-e', to:'f1-elev-e2', big:'Follow the line', sub:'', line:[] },
  /* --- Floor 2: Hauptflur --- */
  { from:'f2-corr-w', to:'f2-elev-w2', big:'Follow the line', sub:'', line:[] },
  { from:'f2-elev-w2', to:'f2-corr-w', big:'Follow the line', sub:'', line:[] },
  { from:'f2-elev-w2', to:'f2-eleve-w', big:'Follow the line', sub:'', line:[] },
  { from:'f2-eleve-w', to:'f2-elev-w2', big:'Follow the line', sub:'', line:[] },
  { from:'f2-eleve-w', to:'f2-elev-w1', big:'Follow the line', sub:'', line:[] },
  { from:'f2-elev-w1', to:'f2-eleve-w', big:'Follow the line', sub:'', line:[] },
  { from:'f2-elev-w1', to:'f2-stair-e2', big:'Follow the line', sub:'', line:[] },
  { from:'f2-stair-e2', to:'f2-elev-w1', big:'Follow the line', sub:'', line:[] },
  { from:'f2-stair-e2', to:'f2-tutor-e1', big:'Follow the line', sub:'', line:[] },
  { from:'f2-tutor-e1', to:'f2-stair-e2', big:'Follow the line', sub:'', line:[] },
  { from:'f2-tutor-e1', to:'f2-stair-e3', big:'Follow the line', sub:'', line:[] },
  { from:'f2-stair-e3', to:'f2-tutor-e1', big:'Follow the line', sub:'', line:[] },
  { from:'f2-stair-e3', to:'f2-elev-ex2', big:'Follow the line', sub:'', line:[] },
  { from:'f2-elev-ex2', to:'f2-stair-e3', big:'Follow the line', sub:'', line:[] },
  { from:'f2-elev-ex2', to:'f2-elev-e', big:'Follow the line', sub:'', line:[] },
  { from:'f2-elev-e', to:'f2-elev-ex2', big:'Follow the line', sub:'', line:[] },
  { from:'f2-elev-e', to:'f2-elev-ex-e', big:'Follow the line', sub:'', line:[] },
  { from:'f2-elev-ex-e', to:'f2-elev-e', big:'Follow the line', sub:'', line:[] },
  { from:'f2-elev-ex-e', to:'f2-corr-e', big:'Follow the line', sub:'', line:[] },
  { from:'f2-corr-e', to:'f2-elev-ex-e', big:'Follow the line', sub:'', line:[] },
  /* Floor 2: West-Spur (hoch) */
  { from:'f2-corr-w', to:'f2-hall-w', big:'Follow the line', sub:'', line:[] },
  { from:'f2-hall-w', to:'f2-corr-w', big:'Follow the line', sub:'', line:[] },
  { from:'f2-hall-w', to:'f2-its-w', big:'Follow the line', sub:'', line:[] },
  { from:'f2-its-w', to:'f2-hall-w', big:'Follow the line', sub:'', line:[] },
  /* Floor 2: Ost-Spur (hoch) */
  { from:'f2-corr-e', to:'f2-hall-e1', big:'Follow the line', sub:'', line:[] },
  { from:'f2-hall-e1', to:'f2-corr-e', big:'Follow the line', sub:'', line:[] },
  { from:'f2-hall-e1', to:'f2-clep-e', big:'Follow the line', sub:'', line:[] },
  { from:'f2-clep-e', to:'f2-hall-e1', big:'Follow the line', sub:'', line:[] },
  /* --- Aufzug Floor 1 <-> Floor 2 --- */
  { from:'f1-elev-w', to:'f2-elev-w1', big:'Take the elevator to Floor 2', sub:'', floor:'Floor 2', elevator:true, line:[] },
  { from:'f2-elev-w1', to:'f1-elev-w', big:'Take the elevator to Floor 1', sub:'', floor:'Floor 1', elevator:true, line:[] },
  { from:'f1-elev-e2', to:'f2-elev-e', big:'Take the elevator to Floor 2', sub:'', floor:'Floor 2', elevator:true, line:[] },
  { from:'f2-elev-e', to:'f1-elev-e2', big:'Take the elevator to Floor 1', sub:'', floor:'Floor 1', elevator:true, line:[] },
  /* --- Floor 3: Hauptflur --- */
  { from:'f3-corr-w', to:'f3-elev-w', big:'Follow the line', sub:'', line:[] },
  { from:'f3-elev-w', to:'f3-corr-w', big:'Follow the line', sub:'', line:[] },
  { from:'f3-elev-w', to:'f3-stair-w2', big:'Follow the line', sub:'', line:[] },
  { from:'f3-stair-w2', to:'f3-elev-w', big:'Follow the line', sub:'', line:[] },
  { from:'f3-stair-w2', to:'f3-vest-e', big:'Follow the line', sub:'', line:[] },
  { from:'f3-vest-e', to:'f3-stair-w2', big:'Follow the line', sub:'', line:[] },
  { from:'f3-vest-e', to:'f3-stair-e2', big:'Follow the line', sub:'', line:[] },
  { from:'f3-stair-e2', to:'f3-vest-e', big:'Follow the line', sub:'', line:[] },
  { from:'f3-stair-e2', to:'f3-elev-e', big:'Follow the line', sub:'', line:[] },
  { from:'f3-elev-e', to:'f3-stair-e2', big:'Follow the line', sub:'', line:[] },
  { from:'f3-elev-e', to:'f3-corr-e', big:'Follow the line', sub:'', line:[] },
  { from:'f3-corr-e', to:'f3-elev-e', big:'Follow the line', sub:'', line:[] },
  /* Floor 3: West-Spur */
  { from:'f3-corr-w', to:'f3-hall-w', big:'Follow the line', sub:'', line:[] },
  { from:'f3-hall-w', to:'f3-corr-w', big:'Follow the line', sub:'', line:[] },
  { from:'f3-hall-w', to:'f3-corner-w1', big:'Follow the line', sub:'', line:[] },
  { from:'f3-corner-w1', to:'f3-hall-w', big:'Follow the line', sub:'', line:[] },
  /* Floor 3: Ost-Spur */
  { from:'f3-corr-e', to:'f3-hall-e', big:'Follow the line', sub:'', line:[] },
  { from:'f3-hall-e', to:'f3-corr-e', big:'Follow the line', sub:'', line:[] },
  { from:'f3-hall-e', to:'f3-corner-e1', big:'Follow the line', sub:'', line:[] },
  { from:'f3-corner-e1', to:'f3-hall-e', big:'Follow the line', sub:'', line:[] },
  /* --- Aufzug Floor 1 <-> Floor 3 --- */
  { from:'f1-elev-w', to:'f3-elev-w', big:'Take the elevator to Floor 3', sub:'', floor:'Floor 3', elevator:true, line:[] },
  { from:'f3-elev-w', to:'f1-elev-w', big:'Take the elevator to Floor 1', sub:'', floor:'Floor 1', elevator:true, line:[] },
  { from:'f1-elev-e2', to:'f3-elev-e', big:'Take the elevator to Floor 3', sub:'', floor:'Floor 3', elevator:true, line:[] },
  { from:'f3-elev-e', to:'f1-elev-e2', big:'Take the elevator to Floor 1', sub:'', floor:'Floor 1', elevator:true, line:[] },
  /* --- Floor 4: Hauptflur --- */
  { from:'f4-corr-w', to:'f4-elev-w', big:'Follow the line', sub:'', line:[] },
  { from:'f4-elev-w', to:'f4-corr-w', big:'Follow the line', sub:'', line:[] },
  { from:'f4-elev-w', to:'f4-stair-w2', big:'Follow the line', sub:'', line:[] },
  { from:'f4-stair-w2', to:'f4-elev-w', big:'Follow the line', sub:'', line:[] },
  { from:'f4-stair-w2', to:'f4-vista-e3', big:'Follow the line', sub:'', line:[] },
  { from:'f4-vista-e3', to:'f4-stair-w2', big:'Follow the line', sub:'', line:[] },
  { from:'f4-vista-e3', to:'f4-stair-e2', big:'Follow the line', sub:'', line:[] },
  { from:'f4-stair-e2', to:'f4-vista-e3', big:'Follow the line', sub:'', line:[] },
  { from:'f4-stair-e2', to:'f4-elev-e-1', big:'Follow the line', sub:'', line:[] },
  { from:'f4-elev-e-1', to:'f4-stair-e2', big:'Follow the line', sub:'', line:[] },
  { from:'f4-elev-e-1', to:'f4-corr-e', big:'Follow the line', sub:'', line:[] },
  { from:'f4-corr-e', to:'f4-elev-e-1', big:'Follow the line', sub:'', line:[] },
  { from:'f4-elev-e-1', to:'f4-elev-e', big:'Follow the line', sub:'', line:[] },
  { from:'f4-elev-e', to:'f4-elev-e-1', big:'Follow the line', sub:'', line:[] },
  /* Floor 4: West-Spur */
  { from:'f4-corr-w', to:'f4-hall-w4', big:'Follow the line', sub:'', line:[] },
  { from:'f4-hall-w4', to:'f4-corr-w', big:'Follow the line', sub:'', line:[] },
  { from:'f4-hall-w4', to:'f4-provost-w1', big:'Follow the line', sub:'', line:[] },
  { from:'f4-provost-w1', to:'f4-hall-w4', big:'Follow the line', sub:'', line:[] },
  /* Floor 4: Ost-Spur */
  { from:'f4-corr-e', to:'f4-wing-e', big:'Follow the line', sub:'', line:[] },
  { from:'f4-wing-e', to:'f4-corr-e', big:'Follow the line', sub:'', line:[] },
  { from:'f4-wing-e', to:'f4-president-e1', big:'Follow the line', sub:'', line:[] },
  { from:'f4-president-e1', to:'f4-wing-e', big:'Follow the line', sub:'', line:[] },
  /* --- Aufzug Floor 1 <-> Floor 4 --- */
  { from:'f1-elev-w', to:'f4-elev-w', big:'Take the elevator to Floor 4', sub:'', floor:'Floor 4', elevator:true, line:[] },
  { from:'f4-elev-w', to:'f1-elev-w', big:'Take the elevator to Floor 1', sub:'', floor:'Floor 1', elevator:true, line:[] },
  { from:'f1-elev-e2', to:'f4-elev-e', big:'Take the elevator to Floor 4', sub:'', floor:'Floor 4', elevator:true, line:[] },
  { from:'f4-elev-e', to:'f1-elev-e2', big:'Take the elevator to Floor 1', sub:'', floor:'Floor 1', elevator:true, line:[] },
];

/* ============================================================
   SICHTBARE RÄUME pro Floor (nur diese erscheinen in Suche/Liste).
   Floors, die hier NICHT gelistet sind, zeigen vorerst ALLE Räume
   (solange wir sie noch nicht kuratiert haben).
   ============================================================ */
const KEEP = {
  1: ['B101','B103','B104','B105','B108','B114','B115','B116','B117','B123','B124','B128','B134','B135','B135A'],
  2: ['B201','B202','B203','B208','B209','B210','B216','B217','B218','B219','B220','B221','B222','B223','B225','B226','B231','B232','B233'],
  3: ['B301','B302','B307','B310','B312','B313','B318','B319','B320','B321','B323','B324','B325','B326','B331','B332','B333','B334','B337','B338','B339','B340','B345','B347','B348','B349','B350','B351'],
  4: ['B401','B402','B405','B410','B411','B416','B417','B418','B419','B420','B421','B427','B428','B429','B434','B435','B439'],
};

/* Räume Floor 1 -> nächster Wegpunkt (Ziel). Ankunft zeigt das Flur-Foto. */
const ROOMS = [
  { id:'B101', wp:'f1-lobby-e1', label:'CAB Lobby' },
  { id:'B101A', wp:'f1-corr-e2' },
  { id:'B101B', wp:'f1-corr-e3' },
  { id:'B102', wp:'f1-lobby-e1' },
  { id:'B103', wp:'f1-lobby-e1', label:'Student Life' },
  { id:'B103A', wp:'f1-lobby-e1' },
  { id:'B103B', wp:'f1-elev-e2' },
  { id:'B103C', wp:'f1-elev-e2' },
  { id:'B103D', wp:'f1-elev-e2' },
  { id:'B103E', wp:'f1-elev-e2' },
  { id:'B103F', wp:'f1-corr-e2' },
  { id:'B103G', wp:'f1-lobby-e1' },
  { id:'B103H', wp:'f1-corr-e2' },
  { id:'B104', wp:'f1-elev-e2', label:'Faculty Offices' },
  { id:'B104A', wp:'f1-elev-e2' },
  { id:'B104B', wp:'f1-elev-e2' },
  { id:'B104C', wp:'f1-elev-e2' },
  { id:'B104D', wp:'f1-elev-e2' },
  { id:'B104E', wp:'f1-elev-e2' },
  { id:'B104F', wp:'f1-elev-e2' },
  { id:'B105', wp:'f1-game-e', label:'Student Lounge / Recreational Sports' },
  { id:'B105A', wp:'f1-game-e' },
  { id:'B105B', wp:'f1-game-e' },
  { id:'B105C', wp:'f1-game-e' },
  { id:'B105D', wp:'f1-game-e' },
  { id:'B106', wp:'f1-game-e' },
  { id:'B106A', wp:'f1-game-e' },
  { id:'B107', wp:'f1-game-e' },
  { id:'B107A', wp:'f1-game-e' },
  { id:'B108', wp:'f1-elev-e2', label:'Food Pantry / Career Clothing' },
  { id:'B108A', wp:'f1-elev-e2' },
  { id:'B109', wp:'f1-elev-e2' },
  { id:'B110', wp:'f1-elev-e2' },
  { id:'B111', wp:'f1-elev-e2' },
  { id:'B111A', wp:'f1-elev-e2' },
  { id:'B112', wp:'f1-elev-e2' },
  { id:'B113', wp:'f1-elev-e2' },
  { id:'B114', wp:'f1-elev-e2', label:'Restroom' },
  { id:'B115', wp:'f1-elev-e2', label:'Restroom' },
  { id:'B116', wp:'f1-elev-e3', label:'Mail and Parking Department' },
  { id:'B116A', wp:'f1-elev-e3' },
  { id:'B116B', wp:'f1-elev-e3' },
  { id:'B117', wp:'f1-elev-e3', label:'Office of Facilities / Construction' },
  { id:'B117A', wp:'f1-elev-e3' },
  { id:'B117B', wp:'f1-elev-e3' },
  { id:'B117C', wp:'f1-elev-e3' },
  { id:'B117D', wp:'f1-elev-e3' },
  { id:'B118', wp:'f1-elev-e3' },
  { id:'B119', wp:'f1-elev-e3' },
  { id:'B120', wp:'f1-corr-w' },
  { id:'B121', wp:'f1-corr-w' },
  { id:'B121A', wp:'f1-corr-w' },
  { id:'B121B', wp:'f1-corr-w' },
  { id:'B121C', wp:'f1-corr-w' },
  { id:'B121D', wp:'f1-corr-w' },
  { id:'B121E', wp:'f1-corr-w' },
  { id:'B122', wp:'f1-corr-w' },
  { id:'B123', wp:'f1-corr-w', label:'Restroom' },
  { id:'B124', wp:'f1-corr-w', label:'Restroom' },
  { id:'B125', wp:'f1-corr-w' },
  { id:'B126', wp:'f1-corr-w' },
  { id:'B127', wp:'f1-corr-w' },
  { id:'B128', wp:'f1-corr-w', label:'Family Restroom' },
  { id:'B129', wp:'f1-corr-w' },
  { id:'B130', wp:'f1-corr-w' },
  { id:'B130A', wp:'f1-corr-w' },
  { id:'B131', wp:'f1-corr-w' },
  { id:'B131A', wp:'f1-corr-w' },
  { id:'B132', wp:'f1-dining-w' },
  { id:'B132A', wp:'f1-corr-w' },
  { id:'B132B', wp:'f1-corr-w' },
  { id:'B133', wp:'f1-dining-w' },
  { id:'B133A', wp:'f1-dining-w' },
  { id:'B133B', wp:'f1-dining-w' },
  { id:'B133C', wp:'f1-dining-w' },
  { id:'B133D', wp:'f1-dining-w' },
  { id:'B134', wp:'f1-dining-w', label:'Dining Hall' },
  { id:'B135', wp:'f1-lobby-e1', label:'Student Lounge' },
  { id:'B135A', wp:'f1-corr-w', label:'TAMUSA Kiosk' },
  { id:'B135B', wp:'f1-corr-w' },
  { id:'B135C', wp:'f1-corr-w' },
  { id:'B135D', wp:'f1-corr-w' },
  { id:'B135E', wp:'f1-corr-e3' },
  /* ---- Floor 2 Räume ---- */
  { id:'B201', wp:'f2-tutor-e1', label:'Lobby' },
  { id:'B202', wp:'f2-tutor-e1', label:'Academic Advising' },
  { id:'B202A', wp:'f2-stair-e2' },
  { id:'B202B', wp:'f2-stair-e2' },
  { id:'B202C', wp:'f2-stair-e2' },
  { id:'B202D', wp:'f2-elev-w1' },
  { id:'B202E', wp:'f2-elev-w1' },
  { id:'B202F', wp:'f2-elev-w1' },
  { id:'B202G', wp:'f2-elev-w1' },
  { id:'B202H', wp:'f2-elev-w2' },
  { id:'B202I', wp:'f2-elev-w2' },
  { id:'B202J', wp:'f2-corr-w' },
  { id:'B202K', wp:'f2-hall-w' },
  { id:'B202L', wp:'f2-hall-w' },
  { id:'B202M', wp:'f2-hall-w' },
  { id:'B202N', wp:'f2-hall-w' },
  { id:'B202O', wp:'f2-hall-w' },
  { id:'B202P', wp:'f2-hall-w' },
  { id:'B202Q', wp:'f2-elev-ex2' },
  { id:'B202R', wp:'f2-stair-e3' },
  { id:'B203', wp:'f2-elev-ex-e', label:'Faculty Offices' },
  { id:'B203A', wp:'f2-elev-ex2' },
  { id:'B203B', wp:'f2-elev-ex2' },
  { id:'B203C', wp:'f2-elev-ex2' },
  { id:'B203D', wp:'f2-hall-e1' },
  { id:'B203E', wp:'f2-hall-e1' },
  { id:'B203F', wp:'f2-hall-e1' },
  { id:'B203G', wp:'f2-elev-ex-e' },
  { id:'B203H', wp:'f2-elev-ex-e' },
  { id:'B203I', wp:'f2-elev-ex2' },
  { id:'B203J', wp:'f2-elev-ex2' },
  { id:'B204', wp:'f2-corr-e' },
  { id:'B205', wp:'f2-corr-e' },
  { id:'B206', wp:'f2-corr-e' },
  { id:'B207', wp:'f2-hall-e1' },
  { id:'B208', wp:'f2-hall-e1', label:'Writing, Language and Digital Composing Center' },
  { id:'B208A', wp:'f2-hall-e1' },
  { id:'B208B', wp:'f2-hall-e1' },
  { id:'B208C', wp:'f2-clep-e' },
  { id:'B209', wp:'f2-clep-e', label:'Testing Center' },
  { id:'B209A', wp:'f2-clep-e' },
  { id:'B209B', wp:'f2-clep-e' },
  { id:'B209C', wp:'f2-clep-e' },
  { id:'B209D', wp:'f2-clep-e' },
  { id:'B210', wp:'f2-clep-e', label:'Disability Support Services' },
  { id:'B210A', wp:'f2-clep-e' },
  { id:'B210B', wp:'f2-clep-e' },
  { id:'B210C', wp:'f2-clep-e' },
  { id:'B210D', wp:'f2-clep-e' },
  { id:'B210E', wp:'f2-clep-e' },
  { id:'B210F', wp:'f2-clep-e' },
  { id:'B210G', wp:'f2-clep-e' },
  { id:'B210H', wp:'f2-clep-e' },
  { id:'B210I', wp:'f2-clep-e' },
  { id:'B210J', wp:'f2-clep-e' },
  { id:'B210K', wp:'f2-clep-e' },
  { id:'B210L', wp:'f2-clep-e' },
  { id:'B210M', wp:'f2-clep-e' },
  { id:'B211A', wp:'f2-clep-e' },
  { id:'B211B', wp:'f2-clep-e' },
  { id:'B211C', wp:'f2-hall-e1' },
  { id:'B211D', wp:'f2-hall-e1' },
  { id:'B211E', wp:'f2-hall-e1' },
  { id:'B211F', wp:'f2-hall-e1' },
  { id:'B211G', wp:'f2-hall-e1' },
  { id:'B212', wp:'f2-hall-e1' },
  { id:'B213', wp:'f2-corr-e' },
  { id:'B214', wp:'f2-corr-e' },
  { id:'B215', wp:'f2-corr-e' },
  { id:'B216', wp:'f2-corr-e', label:'Restroom' },
  { id:'B217', wp:'f2-corr-e', label:'Restroom' },
  { id:'B218', wp:'f2-corr-e', label:'Classroom' },
  { id:'B219', wp:'f2-elev-e', label:'Classroom' },
  { id:'B220', wp:'f2-corr-e', label:'Conference Room' },
  { id:'B221', wp:'f2-stair-e3', label:'Academic Coaching Office' },
  { id:'B222', wp:'f2-stair-e2', label:'Academic Coaching' },
  { id:'B223', wp:'f2-corr-w', label:'Classroom' },
  { id:'B223A', wp:'f2-corr-w' },
  { id:'B224', wp:'f2-corr-w' },
  { id:'B225', wp:'f2-corr-w', label:'Restroom' },
  { id:'B226', wp:'f2-corr-w', label:'Restroom' },
  { id:'B227', wp:'f2-corr-w' },
  { id:'B228', wp:'f2-corr-w' },
  { id:'B229', wp:'f2-corr-w' },
  { id:'B230', wp:'f2-hall-w' },
  { id:'B231', wp:'f2-hall-w', label:'ITS Business' },
  { id:'B231A', wp:'f2-hall-w' },
  { id:'B231B', wp:'f2-hall-w' },
  { id:'B231C', wp:'f2-hall-w' },
  { id:'B231D', wp:'f2-its-w' },
  { id:'B231E', wp:'f2-its-w' },
  { id:'B232', wp:'f2-its-w', label:'Web Dev Team' },
  { id:'B233', wp:'f2-its-w', label:'Information Technology Services' },
  { id:'B233A', wp:'f2-its-w' },
  { id:'B233B', wp:'f2-its-w' },
  { id:'B233C', wp:'f2-its-w' },
  { id:'B233D', wp:'f2-its-w' },
  { id:'B233E', wp:'f2-its-w' },
  { id:'B233F', wp:'f2-its-w' },
  { id:'B233G', wp:'f2-its-w' },
  { id:'B233H', wp:'f2-its-w' },
  { id:'B233I', wp:'f2-its-w' },
  { id:'B233J', wp:'f2-its-w' },
  { id:'B233K', wp:'f2-its-w' },
  { id:'B233L', wp:'f2-its-w' },
  { id:'B233M', wp:'f2-its-w' },
  { id:'B233N', wp:'f2-its-w' },
  { id:'B233O', wp:'f2-its-w' },
  { id:'B233P', wp:'f2-its-w' },
  { id:'B233T', wp:'f2-its-w' },
  { id:'B236', wp:'f2-corr-w' },
  { id:'B237', wp:'f2-corr-w' },
  /* ---- Floor 3 Räume ---- */
  { id:'B301', wp:'f3-vest-e', label:'Lobby' },
  { id:'B301A', wp:'f3-stair-w2' },
  { id:'B301B', wp:'f3-vest-e' },
  { id:'B301C', wp:'f3-stair-e2' },
  { id:'B301D', wp:'f3-stair-w2' },
  { id:'B301E', wp:'f3-stair-w2' },
  { id:'B301F', wp:'f3-stair-e2' },
  { id:'B301G', wp:'f3-stair-e2' },
  { id:'B302', wp:'f3-stair-w2', label:'Biology Lab / Molecular Biology Lab' },
  { id:'B303', wp:'f3-stair-w2' },
  { id:'B304', wp:'f3-stair-w2' },
  { id:'B305', wp:'f3-stair-w2' },
  { id:'B306', wp:'f3-stair-w2' },
  { id:'B307', wp:'f3-vest-e', label:'Chemistry Lab' },
  { id:'B308', wp:'f3-stair-e2' },
  { id:'B309', wp:'f3-stair-e2' },
  { id:'B309A', wp:'f3-stair-e2' },
  { id:'B310', wp:'f3-stair-e2', label:'Biology Lab' },
  { id:'B311', wp:'f3-stair-e2' },
  { id:'B312', wp:'f3-stair-e2', label:'Faculty Office' },
  { id:'B313', wp:'f3-corr-e', label:'History and Philosophy Faculty Office' },
  { id:'B313A', wp:'f3-elev-e' },
  { id:'B313B', wp:'f3-elev-e' },
  { id:'B313C', wp:'f3-elev-e' },
  { id:'B313D', wp:'f3-stair-e2' },
  { id:'B313E', wp:'f3-hall-e' },
  { id:'B313F', wp:'f3-hall-e' },
  { id:'B313G', wp:'f3-hall-e' },
  { id:'B313H', wp:'f3-hall-e' },
  { id:'B313I', wp:'f3-hall-e' },
  { id:'B313J', wp:'f3-hall-e' },
  { id:'B314', wp:'f3-corr-e' },
  { id:'B315', wp:'f3-corr-e' },
  { id:'B316', wp:'f3-corr-e' },
  { id:'B317', wp:'f3-hall-e' },
  { id:'B318', wp:'f3-hall-e', label:'Faculty Offices' },
  { id:'B318A', wp:'f3-hall-e' },
  { id:'B318B', wp:'f3-hall-e' },
  { id:'B318C', wp:'f3-hall-e' },
  { id:'B318D', wp:'f3-hall-e' },
  { id:'B319', wp:'f3-corner-e1', label:'Faculty Office' },
  { id:'B319A', wp:'f3-corner-e1' },
  { id:'B319B', wp:'f3-corner-e1' },
  { id:'B319C', wp:'f3-corner-e1' },
  { id:'B319D', wp:'f3-corner-e1' },
  { id:'B320', wp:'f3-corner-e1', label:'Jaguar Student Media / Newsroom' },
  { id:'B320A', wp:'f3-corner-e1' },
  { id:'B320B', wp:'f3-corner-e1' },
  { id:'B320C', wp:'f3-corner-e1' },
  { id:'B320D', wp:'f3-corner-e1' },
  { id:'B320E', wp:'f3-corner-e1' },
  { id:'B320F', wp:'f3-corner-e1' },
  { id:'B320G', wp:'f3-corner-e1' },
  { id:'B321', wp:'f3-corner-e1', label:'Faculty Office' },
  { id:'B322', wp:'f3-corner-e1' },
  { id:'B323', wp:'f3-hall-e', label:'Faculty Office' },
  { id:'B324', wp:'f3-hall-e', label:'Faculty Office' },
  { id:'B325', wp:'f3-hall-e', label:'Faculty Office' },
  { id:'B326', wp:'f3-hall-e', label:'Faculty Office' },
  { id:'B327', wp:'f3-hall-e' },
  { id:'B328', wp:'f3-corr-e' },
  { id:'B329', wp:'f3-corr-e' },
  { id:'B330', wp:'f3-corr-e' },
  { id:'B331', wp:'f3-corr-e', label:'Restroom' },
  { id:'B332', wp:'f3-corr-e', label:'Restroom' },
  { id:'B333', wp:'f3-corr-e', label:'Classroom' },
  { id:'B334', wp:'f3-corr-e', label:'Classroom' },
  { id:'B335', wp:'f3-vest-e' },
  { id:'B336', wp:'f3-vest-e' },
  { id:'B337', wp:'f3-corr-w', label:'Classroom' },
  { id:'B338', wp:'f3-corr-w', label:'Classroom' },
  { id:'B339', wp:'f3-corr-w', label:'Restroom' },
  { id:'B340', wp:'f3-corr-w', label:'Restroom' },
  { id:'B341', wp:'f3-corr-w' },
  { id:'B342', wp:'f3-corr-w' },
  { id:'B343', wp:'f3-corr-w' },
  { id:'B344', wp:'f3-hall-w' },
  { id:'B345', wp:'f3-hall-w', label:'Early College and Academic Partnership Department' },
  { id:'B345A', wp:'f3-hall-w' },
  { id:'B345B', wp:'f3-hall-w' },
  { id:'B345C', wp:'f3-hall-w' },
  { id:'B345D', wp:'f3-hall-w' },
  { id:'B346', wp:'f3-corner-w1' },
  { id:'B347', wp:'f3-corner-w1', label:'Department of Sociology and Communication' },
  { id:'B347A', wp:'f3-corner-w1' },
  { id:'B347B', wp:'f3-corner-w1' },
  { id:'B347C', wp:'f3-corner-w1' },
  { id:'B347D', wp:'f3-corner-w1' },
  { id:'B347E', wp:'f3-corner-w1' },
  { id:'B347F', wp:'f3-corner-w1' },
  { id:'B347G', wp:'f3-corner-w1' },
  { id:'B347H', wp:'f3-corner-w1' },
  { id:'B348', wp:'f3-corner-w1', label:'Faculty Office' },
  { id:'B348A', wp:'f3-corner-w1' },
  { id:'B348B', wp:'f3-corner-w1' },
  { id:'B348C', wp:'f3-corner-w1' },
  { id:'B348D', wp:'f3-corner-w1' },
  { id:'B348E', wp:'f3-corner-w1' },
  { id:'B348F', wp:'f3-corner-w1' },
  { id:'B349', wp:'f3-corner-w1', label:'Faculty Office' },
  { id:'B349A', wp:'f3-corner-w1' },
  { id:'B349B', wp:'f3-corner-w1' },
  { id:'B349C', wp:'f3-corner-w1' },
  { id:'B349D', wp:'f3-corner-w1' },
  { id:'B350', wp:'f3-hall-w', label:'Sociology Office' },
  { id:'B350A', wp:'f3-hall-w' },
  { id:'B350B', wp:'f3-hall-w' },
  { id:'B350C', wp:'f3-hall-w' },
  { id:'B350D', wp:'f3-hall-w' },
  { id:'B351', wp:'f3-hall-w', label:'Public Health Office' },
  { id:'B351A', wp:'f3-hall-w' },
  { id:'B351B', wp:'f3-hall-w' },
  { id:'B351C', wp:'f3-hall-w' },
  { id:'B351D', wp:'f3-hall-w' },
  { id:'B351E', wp:'f3-stair-w2' },
  { id:'B351F', wp:'f3-hall-w' },
  { id:'B351G', wp:'f3-hall-w' },
  { id:'B351H', wp:'f3-hall-w' },
  { id:'B351I', wp:'f3-hall-w' },
  { id:'B352', wp:'f3-corr-w' },
  { id:'B353', wp:'f3-corr-w' },
  { id:'B354', wp:'f3-elev-w' },
  /* ---- Floor 4 Räume ---- */
  { id:'B401', wp:'f4-vista-e3', label:'Lobby, Fourth Floor' },
  { id:'B402', wp:'f4-vista-e3', label:'Vista Room' },
  { id:'B402A', wp:'f4-vista-e3' },
  { id:'B402B', wp:'f4-stair-w2' },
  { id:'B402C', wp:'f4-stair-e2' },
  { id:'B403', wp:'f4-stair-w2' },
  { id:'B404', wp:'f4-stair-e2' },
  { id:'B405', wp:'f4-elev-e-1', label:'University Advancement' },
  { id:'B405A', wp:'f4-elev-e-1' },
  { id:'B405B', wp:'f4-elev-e-1' },
  { id:'B405C', wp:'f4-elev-e-1' },
  { id:'B405D', wp:'f4-elev-e-1' },
  { id:'B405E', wp:'f4-stair-e2' },
  { id:'B405F', wp:'f4-stair-e2' },
  { id:'B405G', wp:'f4-stair-e2' },
  { id:'B405H', wp:'f4-elev-e-1' },
  { id:'B405I', wp:'f4-elev-e-1' },
  { id:'B405J', wp:'f4-wing-e' },
  { id:'B405K', wp:'f4-wing-e' },
  { id:'B405L', wp:'f4-wing-e' },
  { id:'B405M', wp:'f4-wing-e' },
  { id:'B405N', wp:'f4-elev-e-1' },
  { id:'B405O', wp:'f4-elev-e-1' },
  { id:'B406', wp:'f4-corr-e' },
  { id:'B406A', wp:'f4-corr-e' },
  { id:'B407', wp:'f4-corr-e' },
  { id:'B408', wp:'f4-wing-e' },
  { id:'B409', wp:'f4-president-e1', label:'Office of the President' },
  { id:'B409A', wp:'f4-wing-e' },
  { id:'B409B', wp:'f4-wing-e' },
  { id:'B409C', wp:'f4-president-e1' },
  { id:'B409D', wp:'f4-president-e1' },
  { id:'B410', wp:'f4-president-e1', label:'Office of the President' },
  { id:'B410A', wp:'f4-president-e1' },
  { id:'B410B', wp:'f4-president-e1' },
  { id:'B410C', wp:'f4-president-e1' },
  { id:'B410D', wp:'f4-president-e1' },
  { id:'B410E', wp:'f4-president-e1' },
  { id:'B410G', wp:'f4-president-e1' },
  { id:'B410J', wp:'f4-corr-e' },
  { id:'B410K', wp:'f4-president-e1' },
  { id:'B411', wp:'f4-wing-e', label:'Marketing and Strategic Communications Office' },
  { id:'B411A', wp:'f4-president-e1' },
  { id:'B411B', wp:'f4-president-e1' },
  { id:'B411C', wp:'f4-president-e1' },
  { id:'B411D', wp:'f4-wing-e' },
  { id:'B411E', wp:'f4-wing-e' },
  { id:'B411F', wp:'f4-wing-e' },
  { id:'B411G', wp:'f4-wing-e' },
  { id:'B411H', wp:'f4-wing-e' },
  { id:'B412', wp:'f4-wing-e' },
  { id:'B413', wp:'f4-wing-e' },
  { id:'B414', wp:'f4-corr-e' },
  { id:'B415', wp:'f4-corr-e' },
  { id:'B416', wp:'f4-corr-e', label:'Restroom' },
  { id:'B417', wp:'f4-corr-e', label:'Restroom' },
  { id:'B418', wp:'f4-corr-e', label:'Office of Business Affairs' },
  { id:'B418A', wp:'f4-corr-e' },
  { id:'B418B', wp:'f4-corr-e' },
  { id:'B418C', wp:'f4-corr-e' },
  { id:'B418D', wp:'f4-corr-e' },
  { id:'B418E', wp:'f4-corr-e' },
  { id:'B418F', wp:'f4-corr-e' },
  { id:'B418G', wp:'f4-corr-e' },
  { id:'B418H', wp:'f4-corr-e' },
  { id:'B418I', wp:'f4-corr-e' },
  { id:'B419', wp:'f4-corr-e', label:'Conference Room, Finance and Administration' },
  { id:'B420', wp:'f4-elev-e', label:'Finance and Administration Break Room' },
  { id:'B421', wp:'f4-elev-e', label:'Faculty Office' },
  { id:'B422', wp:'f4-vista-e3' },
  { id:'B423', wp:'f4-vista-e3' },
  { id:'B424', wp:'f4-elev-w' },
  { id:'B425', wp:'f4-corr-w' },
  { id:'B426', wp:'f4-corr-w' },
  { id:'B427', wp:'f4-corr-w', label:'Office of the Vice President of Research' },
  { id:'B427A', wp:'f4-corr-w' },
  { id:'B427B', wp:'f4-corr-w' },
  { id:'B427C', wp:'f4-corr-w' },
  { id:'B427D', wp:'f4-corr-w' },
  { id:'B427E', wp:'f4-corr-w' },
  { id:'B427F', wp:'f4-corr-w' },
  { id:'B427G', wp:'f4-corr-w' },
  { id:'B427H', wp:'f4-corr-w' },
  { id:'B428', wp:'f4-corr-w', label:'Restroom' },
  { id:'B429', wp:'f4-corr-w', label:'Restroom' },
  { id:'B430', wp:'f4-corr-w' },
  { id:'B431', wp:'f4-corr-w' },
  { id:'B432', wp:'f4-hall-w4' },
  { id:'B433', wp:'f4-hall-w4' },
  { id:'B434', wp:'f4-provost-w1', label:'Operations, Environmental Health and Safety' },
  { id:'B434A', wp:'f4-hall-w4' },
  { id:'B434B', wp:'f4-hall-w4' },
  { id:'B434C', wp:'f4-provost-w1' },
  { id:'B434D', wp:'f4-provost-w1' },
  { id:'B434E', wp:'f4-provost-w1' },
  { id:'B434F', wp:'f4-provost-w1' },
  { id:'B434G', wp:'f4-provost-w1' },
  { id:'B435', wp:'f4-provost-w1', label:'Office of the Provost' },
  { id:'B435A', wp:'f4-provost-w1' },
  { id:'B435B', wp:'f4-provost-w1' },
  { id:'B435C', wp:'f4-provost-w1' },
  { id:'B435D', wp:'f4-provost-w1' },
  { id:'B435E', wp:'f4-provost-w1' },
  { id:'B435F', wp:'f4-provost-w1' },
  { id:'B435G', wp:'f4-provost-w1' },
  { id:'B435H', wp:'f4-provost-w1' },
  { id:'B435I', wp:'f4-provost-w1' },
  { id:'B435J', wp:'f4-provost-w1' },
  { id:'B435K', wp:'f4-provost-w1' },
  { id:'B436A', wp:'f4-provost-w1' },
  { id:'B436B', wp:'f4-provost-w1' },
  { id:'B436C', wp:'f4-hall-w4' },
  { id:'B436D', wp:'f4-hall-w4' },
  { id:'B436E', wp:'f4-hall-w4' },
  { id:'B436F', wp:'f4-hall-w4' },
  { id:'B436G', wp:'f4-hall-w4' },
  { id:'B436N', wp:'f4-provost-w1' },
  { id:'B437', wp:'f4-corr-w' },
  { id:'B438', wp:'f4-corr-w' },
  { id:'B439', wp:'f4-elev-w', label:'Human Resources (HR)' },
  { id:'B439A', wp:'f4-corr-w' },
  { id:'B439B', wp:'f4-elev-w' },
  { id:'B439C', wp:'f4-corr-w' },
  { id:'B439D', wp:'f4-corr-w' },
  { id:'B439E', wp:'f4-hall-w4' },
  { id:'B439F', wp:'f4-hall-w4' },
  { id:'B439G', wp:'f4-hall-w4' },
  { id:'B439H', wp:'f4-elev-w' },
  { id:'B439I', wp:'f4-stair-w2' },
  { id:'B439J', wp:'f4-stair-w2' },
  { id:'B439K', wp:'f4-stair-w2' },
  { id:'B439L', wp:'f4-stair-w2' },
  { id:'B439M', wp:'f4-stair-w2' },
  { id:'B439N', wp:'f4-stair-w2' },
  { id:'B439O', wp:'f4-stair-w2' },
  { id:'B439P', wp:'f4-elev-w' },
  { id:'B439Q', wp:'f4-elev-w' },
  { id:'B441A', wp:'f4-stair-w2' },
  { id:'B441B', wp:'f4-elev-e-1' },
];

/* ============================================================
   RAUM-LABELS (was ist der Raum) — aus der Tabelle.
   Wird in Suchliste, Ziel-Kopf und Ankunft angezeigt und ist suchbar.
   Leer/fehlt = es wird nur die Raumnummer gezeigt.
   ============================================================ */
const LABELS = {
  "B101": "CAB Lobby",
  "B103": "Student Life",
  "B104": "Faculty Offices",
  "B105": "Student Lounge / Recreational Sports",
  "B108": "Office",
  "B114": "Restroom",
  "B115": "Restroom",
  "B116": "Mail and Receiving Department",
  "B117": "Office of Facilities / Construction",
  "B123": "Restroom",
  "B124": "Restroom",
  "B128": "Family Restroom",
  "B134": "Dining Hall",
  "B135": "Student Lounge",
  "B135A": "TAMUSA Kiosk",
  "B201": "Lobby",
  "B202": "Academic Advising",
  "B203": "Faculty Offices",
  "B208": "Writing, Language and Digital Composing Center",
  "B209": "Testing Center",
  "B210": "Disability Support Services",
  "B216": "Restroom",
  "B217": "Restroom",
  "B218": "Classroom",
  "B219": "Classroom",
  "B220": "Conference Room",
  "B221": "Academic Coaching Office",
  "B222": "Academic Coaching",
  "B223": "Classroom",
  "B225": "Restroom",
  "B226": "Restroom",
  "B231": "ITS Business",
  "B232": "Web Dev Team",
  "B233": "Information Technology Services",
  "B301": "Lobby",
  "B302": "Biology Lab / Molecular Biology Lab",
  "B307": "Chemistry Lab",
  "B310": "Biology Lab",
  "B312": "Faculty Office",
  "B313": "History and Philosophy Faculty Office",
  "B318": "Faculty Offices",
  "B319": "Faculty Office",
  "B320": "Jaguar Student Media / Newsroom",
  "B321": "Faculty Office",
  "B323": "Faculty Office",
  "B324": "Faculty Office",
  "B325": "Faculty Office",
  "B326": "Faculty Office",
  "B331": "Restroom",
  "B332": "Restroom",
  "B333": "Classroom",
  "B334": "Classroom",
  "B337": "Classroom",
  "B338": "Classroom",
  "B339": "Restroom",
  "B340": "Restroom",
  "B345": "Early College and Academic Partnership Department",
  "B347": "Department of Sociology and Communication",
  "B348": "Faculty Office",
  "B349": "Faculty Office",
  "B350": "Sociology Office",
  "B351": "Public Health Office",
  "B401": "Lobby, Fourth Floor",
  "B402": "Vista Room",
  "B405": "University Advancement",
  "B409": "Office of the President",
  "B410": "Office of the President",
  "B411": "Marketing and Strategic Communications Office",
  "B416": "Restroom",
  "B417": "Restroom",
  "B418": "Office of Business Affairs",
  "B419": "Conference Room, Finance and Administration",
  "B420": "Finance and Administration Break Room",
  "B421": "Faculty Office",
  "B427": "Office of the Vice President of Research",
  "B428": "Restroom",
  "B429": "Restroom",
  "B434": "Operations, Environmental Health and Safety",
  "B435": "Office of the Provost",
  "B439": "Human Resources (HR)",
};
